"""Transaction and storage ports used only by hosted publisher application services."""

from collections.abc import Iterator
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol
from uuid import UUID

from nervos_marketplace_service.domain.artifact_reference import FinalizedArtifactRef
from nervos_marketplace_service.domain.identity import Record


class IdentityTransaction(Protocol):
    def get(self, table: str, where: Record, *, lock: bool = True) -> Record: ...
    def find(self, table: str, where: Record, *, limit: int = 100) -> list[Record]: ...
    def insert(self, table: str, values: Record) -> None: ...
    def update(self, table: str, where: Record, values: Record) -> None: ...
    def audit(self, actor: UUID | None, action: str, target: str, evidence: Record) -> None: ...
    def rate_limit(self, account_id: UUID, action: str, maximum: int) -> None: ...
    def upload_capacity(self, account_id: UUID, publisher_id: UUID) -> tuple[int, int, int]: ...


class PublicationUnitOfWork(Protocol):
    def transaction(
        self, request_id: str = "system"
    ) -> AbstractContextManager[IdentityTransaction]: ...


class PublicationStorage(Protocol):
    def quarantine(self, operation_id: UUID, digest: str, path: Path, size: int) -> None: ...
    def retrieve(self, operation_id: UUID, digest: str, size: int, destination: Path) -> None: ...
    def finalize(self, digest: str, path: Path, size: int) -> FinalizedArtifactRef: ...
    def available(self, reference: FinalizedArtifactRef) -> bool: ...
    def delete_quarantine(self, operation_id: UUID, digest: str) -> None: ...
    def close(self) -> None: ...


class StaticPackageVerifier(Protocol):
    def verify(self, path: Path) -> Record: ...


class ByteSource(Protocol):
    def chunks(self) -> Iterator[bytes]: ...
