# ruff: noqa: E501
"""stage c1 durable execution

Revision ID: 0003_stage_c1_durable_execution
Revises: 0002_stage_b1_agent_instances_runs
Create Date: 2026-09-14 17:41:52.780790
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nervos_core.infrastructure.database.types import UTCDateTime

revision: str = "0003_stage_c1_durable_execution"
down_revision: str | None = "0002_stage_b1_agent_instances_runs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("agent_instance_id", sa.Integer(), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("available_at", UTCDateTime(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("cancel_requested_at", UTCDateTime(), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("claim_token", sa.LargeBinary(length=32), nullable=True),
        sa.Column("lease_expires_at", UTCDateTime(), nullable=True),
        sa.Column("last_heartbeat_at", UTCDateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','claimed','running','retry_wait','succeeded','failed','cancelled')",
            name=op.f("ck_jobs_status_value"),
        ),
        sa.CheckConstraint(
            "attempt_count BETWEEN 0 AND max_attempts AND max_attempts BETWEEN 1 AND 10",
            name=op.f("ck_jobs_attempt_bounds"),
        ),
        sa.CheckConstraint(
            "length(model_provider) BETWEEN 1 AND 64", name=op.f("ck_jobs_model_provider_shape")
        ),
        sa.CheckConstraint(
            "(claimed_by IS NULL AND claim_token IS NULL AND lease_expires_at IS NULL AND last_heartbeat_at IS NULL) OR (claimed_by IS NOT NULL AND length(claimed_by) BETWEEN 1 AND 128 AND claim_token IS NOT NULL AND length(claim_token)=32 AND lease_expires_at IS NOT NULL AND last_heartbeat_at IS NOT NULL)",
            name=op.f("ck_jobs_claim_shape"),
        ),
        sa.CheckConstraint(
            "(error_code IS NULL) = (error_message IS NULL)", name=op.f("ck_jobs_error_pair")
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR (length(error_code) BETWEEN 1 AND 64 AND length(error_message) BETWEEN 1 AND 512)",
            name=op.f("ck_jobs_error_bounds"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at AND available_at >= created_at AND (finished_at IS NULL OR finished_at >= created_at) AND (cancel_requested_at IS NULL OR cancel_requested_at >= created_at)",
            name=op.f("ck_jobs_timestamp_order"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded','failed','cancelled')) = (finished_at IS NOT NULL)",
            name=op.f("ck_jobs_terminal_finish"),
        ),
        sa.CheckConstraint(
            "(status IN ('failed','cancelled')) = (error_code IS NOT NULL)",
            name=op.f("ck_jobs_terminal_error"),
        ),
        sa.CheckConstraint(
            "status != 'cancelled' OR cancel_requested_at IS NOT NULL",
            name=op.f("ck_jobs_cancelled_request"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["agent_instances.id"],
            name=op.f("fk_jobs_agent_instance_id_agent_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_jobs_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_jobs_run_id")),
        sqlite_autoincrement=True,
    )
    op.create_index(
        "ix_jobs_agent_instance_id_status", "jobs", ["agent_instance_id", "status"], unique=False
    )
    op.create_index(
        "ix_jobs_status_available_at_id", "jobs", ["status", "available_at", "id"], unique=False
    )
    op.create_index(
        "ix_jobs_status_lease_expires_at_id",
        "jobs",
        ["status", "lease_expires_at", "id"],
        unique=False,
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("claim_token", sa.LargeBinary(length=32), nullable=False),
        sa.Column("claimed_at", UTCDateTime(), nullable=False),
        sa.Column("execution_started_at", UTCDateTime(), nullable=True),
        sa.Column("lease_expires_at", UTCDateTime(), nullable=False),
        sa.Column("last_heartbeat_at", UTCDateTime(), nullable=False),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.Column("retry_disposition", sa.String(length=20), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_job_attempts_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "status IN ('claimed','running','succeeded','failed','cancelled','expired')",
            name=op.f("ck_job_attempts_status_value"),
        ),
        sa.CheckConstraint(
            "length(worker_id) BETWEEN 1 AND 128 AND length(claim_token)=32",
            name=op.f("ck_job_attempts_owner_shape"),
        ),
        sa.CheckConstraint(
            "lease_expires_at > claimed_at AND last_heartbeat_at >= claimed_at AND created_at >= claimed_at",
            name=op.f("ck_job_attempts_lease_order"),
        ),
        sa.CheckConstraint(
            "execution_started_at IS NULL OR execution_started_at >= claimed_at",
            name=op.f("ck_job_attempts_start_order"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= COALESCE(execution_started_at, claimed_at)",
            name=op.f("ck_job_attempts_finish_order"),
        ),
        sa.CheckConstraint(
            "retry_disposition IS NULL OR retry_disposition IN ('SAFE_TO_RETRY','DO_NOT_RETRY','AMBIGUOUS')",
            name=op.f("ck_job_attempts_retry_disposition_value"),
        ),
        sa.CheckConstraint(
            "(error_code IS NULL) = (error_message IS NULL)",
            name=op.f("ck_job_attempts_error_pair"),
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR (length(error_code) BETWEEN 1 AND 64 AND length(error_message) BETWEEN 1 AND 512)",
            name=op.f("ck_job_attempts_error_bounds"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded','failed','cancelled','expired')) = (finished_at IS NOT NULL)",
            name=op.f("ck_job_attempts_terminal_finish"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('claimed','running') OR (finished_at IS NULL AND retry_disposition IS NULL AND error_code IS NULL)",
            name=op.f("ck_job_attempts_active_shape"),
        ),
        sa.CheckConstraint(
            "status != 'claimed' OR execution_started_at IS NULL",
            name=op.f("ck_job_attempts_claimed_shape"),
        ),
        sa.CheckConstraint(
            "status != 'running' OR execution_started_at IS NOT NULL",
            name=op.f("ck_job_attempts_running_shape"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('failed','expired') OR retry_disposition IS NOT NULL",
            name=op.f("ck_job_attempts_failure_disposition"),
        ),
        sa.CheckConstraint(
            "status != 'succeeded' OR (retry_disposition IS NULL AND error_code IS NULL)",
            name=op.f("ck_job_attempts_success_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_attempts_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint("job_id", "attempt_number", name=op.f("uq_job_attempts_job_id")),
        sqlite_autoincrement=True,
    )
    op.create_index(
        "ix_job_attempts_status_lease_expires_at_id",
        "job_attempts",
        ["status", "lease_expires_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_job_attempts_one_active",
        "job_attempts",
        ["job_id"],
        unique=True,
        sqlite_where=sa.text("status IN ('claimed','running')"),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("message", sa.String(length=512), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=True),
        sa.Column("available_at", UTCDateTime(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_run_events_sequence_positive")),
        sa.CheckConstraint(
            "event_type IN ('run.created','run.queued','attempt.claimed','attempt.started','attempt.failed','attempt.expired','retry.scheduled','cancellation.requested','run.cancelled','run.succeeded','run.failed','recovery.pre_start','recovery.ambiguous')",
            name=op.f("ck_run_events_event_type_value"),
        ),
        sa.CheckConstraint(
            "(code IS NULL) = (message IS NULL)", name=op.f("ck_run_events_message_pair")
        ),
        sa.CheckConstraint(
            "code IS NULL OR (length(code) BETWEEN 1 AND 64 AND length(message) BETWEEN 1 AND 512)",
            name=op.f("ck_run_events_message_bounds"),
        ),
        sa.CheckConstraint(
            "attempt_number IS NULL OR attempt_number > 0",
            name=op.f("ck_run_events_attempt_number_positive"),
        ),
        sa.CheckConstraint(
            "event_type != 'retry.scheduled' OR available_at IS NOT NULL",
            name=op.f("ck_run_events_retry_available"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["job_attempts.id"],
            name=op.f("fk_run_events_attempt_id_job_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_run_events_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "sequence", name=op.f("uq_run_events_run_id")),
        sqlite_autoincrement=True,
    )
    op.create_index("ix_run_events_attempt_id_id", "run_events", ["attempt_id", "id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_events_attempt_id_id", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(
        "uq_job_attempts_one_active",
        table_name="job_attempts",
        sqlite_where=sa.text("status IN ('claimed','running')"),
    )
    op.drop_index("ix_job_attempts_status_lease_expires_at_id", table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_index("ix_jobs_status_lease_expires_at_id", table_name="jobs")
    op.drop_index("ix_jobs_status_available_at_id", table_name="jobs")
    op.drop_index("ix_jobs_agent_instance_id_status", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
